# Generated by Django 4.2.3 on 2024-04-06 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место для привычки')),
                ('time', models.DateTimeField(verbose_name='время для привычки')),
                ('action', models.CharField(max_length=500, verbose_name='действие привычки')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('is_useful', models.BooleanField(blank=True, default=False, null=True, verbose_name='Связанная, полезная привычка')),
                ('periodicity', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'раз в неделю')], default='daily', verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('link_pleasant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Ссылка на приятную привычку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
